version: '3.8'

services:
  dns-scanner:
    build:
      context: .
      dockerfile: Dockerfile.azure
    container_name: dns-scanner
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    volumes:
      # Persist wordlists and add your own
      - wordlists:/app/wordlists
      # Optional: Mount custom templates to override defaults
      #- ./templates:/app/templates
      # Optional: Mount custom static files
      #- ./static:/app/static
    restart: unless-stopped
    environment:
      - TZ=UTC
      # Database configuration matching Azure PostgreSQL Flexible Server
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=dnsscanner
      - DB_PASSWORD=securepassword
      - DB_NAME=dnsscanner
      - DB_SSLMODE=disable
      # Azure Application Insights (optional)
      - APPLICATIONINSIGHTS_CONNECTION_STRING=${APPLICATIONINSIGHTS_CONNECTION_STRING}
      # Optional: OpenAI API key for AI-powered wordlist generation
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    networks:
      - dns-scanner-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

  postgres:
    image: postgres:14-alpine
    container_name: dns-scanner-db
    environment:
      - POSTGRES_USER=dnsscanner
      - POSTGRES_PASSWORD=securepassword
      - POSTGRES_DB=dnsscanner
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - dns-scanner-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dnsscanner"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  # Azure Storage Emulator - for local testing
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: dns-scanner-storage
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"
    volumes:
      - azurite-data:/data
    networks:
      - dns-scanner-network

volumes:
  wordlists:
    name: dns-scanner-wordlists
  postgres-data:
    name: dns-scanner-db-data
  azurite-data:
    name: dns-scanner-azurite-data

networks:
  dns-scanner-network:
    name: dns-scanner-network
