version: '3.8'

services:
  dns-scanner:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dns-scanner
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    volumes:
      # Persist wordlists and add your own
      - wordlists:/app/wordlists
      # Optional: Mount custom templates to override defaults
      #- ./templates:/app/templates
      # Optional: Mount custom static files
      #- ./static:/app/static
    restart: unless-stopped
    environment:
      - TZ=UTC
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=dnsscanner
      - DB_PASSWORD=securepassword
      - DB_NAME=dnsscanner
      - DB_SSLMODE=disable
      # Optional: OpenAI API key for AI-powered wordlist generation
      # - OPENAI_API_KEY=your_api_key_here
    networks:
      - dns-scanner-network

  postgres:
    image: postgres:14-alpine
    container_name: dns-scanner-db
    environment:
      - POSTGRES_USER=dnsscanner
      - POSTGRES_PASSWORD=securepassword
      - POSTGRES_DB=dnsscanner
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - dns-scanner-network
    command: ["postgres", "-c", "log_statement=all"]

volumes:
  wordlists:
    name: dns-scanner-wordlists
  postgres-data:
    name: dns-scanner-db-data

networks:
  dns-scanner-network:
    name: dns-scanner-network